### ISSUE TITLE
Override HttpClient creation

### ISSUE THREAD

**Issue by brettmas** [seek-oss/ad-posting-api-client#3]
Would be great if we could either pass through our own HttpClient, or our own HttpMessageHandler so that we can inject our own request logging.

**Comment by ConradLang** [comment]
@brettmas: We've updated the API client with improved exceptions. You can get the response status code as well as the response content for logging.

See https://github.com/SEEK-Jobs/ad-posting-api-client/releases/tag/1.3.0

If this is adequate, I'll close this issue.

**Comment by zsims** [comment]
[Release 2.0.667](https://github.com/seek-oss/ad-posting-api-client/releases/tag/2.0.667) now has support for providing a custom `DelegatingHandler` which will let you log requests and responses.

There's a brief example of using this in the README.
